apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
  labels:
    app: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: mlops-container
        image: your-dockerhub/mlops-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
